### ISSUE TITLE
Want to know if this repository is to create new website for bench routes?

### ISSUE THREAD

**Issue by divyagar** [bench-routes/benchdocs#1]
I want to know if this repository is for "Revamping the UI" idea on GSOC ideas list?

**Comment by harkishen** [comment]
**Revamping the UI** is for UI of benchroutes. This is the website which we are developing at the moment. I don't think this is going to be in the idea list.

**Comment by muskankhedia** [comment]
I feel this issue is resolved. Hence closing it.
